name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg     # headless plotting for any matplotlib usage

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure core scientific stack & test tools even if requirements.txt is minimal
          pip install numpy scipy matplotlib pytest pytest-cov

      - name: Run tests
        run: |
          pytest -q